email: kevcon80@gmail.com
full_name: Kevin Conti
name: Kevin
background: Applied AI Software Engineer focused on entrepreneurial and innovative projects
schedule_preferences: Meetings are rare and should only be scheduled when specifically instructed
background_preferences: This is a personal email account with no specific coworkers to loop in
response_preferences: Prioritize direct and efficient communication
timezone: "EST"
rewrite_preferences: |
  Kevin has a few rules for how he likes his emails to be written:

  - He generally likes to match their tone. If they write formally, then so will he. If they write casually, then he should write casual
  - If working with an assistant to schedule, then he is usually more formal
  - If conversing with someone he seems to know well, then he is more direct and to the fact
  - Kevin REALLY does not want anyone to know he is using an assistant, so you should try not to sound too much like an assistant and rather sound like Kevin
  - When Kevin is casual, he generally does not include any greetings or sign offs, and just directly says his message

triage_no: |
  - Automated service emails
  - Cold sales outreach
  - Unsolicited meeting requests

triage_notify: |
  - Urgent or time-sensitive communications
  - Opportunities that align with professional interests
  - Personal or professional development inquiries

triage_email: |
  - Emails that require a thoughtful, personalized response
  - Emails that seem to be sent from a real person that are NOT cold outreach. 

memory: true
